FROM python:3.9
LABEL maintainer=test@example.com
RUN pip install fastapi
CMD ["python", "app.py"]
LABEL org.opencontainers.image.version=1.2.3 org.opencontainers.image.devmode=true org.opencontainers.image.noscan=false org.opencontainers.image.platform=arm
