FROM python:3.9
LABEL maintainer=test@example.com
RUN pip install fastapi
CMD ["python", "app.py"]
LABEL org.opencontainers.image.version=1.0.0 org.opencontainers.image.devmode=false org.opencontainers.image.noscan=false org.opencontainers.image.platform=x86
